// Create a new account from goLand IDE

POST http://localhost:5000/accounts
content-Type:  application/json

{
  "owner" : "wallace machado",
  "currency": "EUR"
}

###

// Get a account from goLand IDE

GET http://localhost:5000/accounts/1
accept:  application/json

###

// Get accounts from goLand IDE

GET http://localhost:5000/accounts?page_id=1&page_size=5
accept:  application/json

###

// Create a new transfer from goLand IDE




POST http://localhost:5000/transfers
content-Type:  application/json

{
"from_account_id": 1,
"to_account_id": 2,
"Amount": 10,
"currency": "EUR"

}
###

POST http://localhost:5000/users
content-Type:  application/json

{
"username":"testename",
"password": "testepass",
"full_name": "testefullname",
"email":"a@b.com"

}

###
POST http://localhost:5000/users
content-Type:  application/json

{
  "username":"testename2",
  "password": "testepass2",
  "full_name": "testefullname2",
  "email":"a2@b.com"

}
###
POST http://localhost:5000/users/login
content-Type:  application/json

{
  "username":"testename",
  "password": "testepass"

}
###

POST http://localhost:5000/users/login
content-Type:  application/json

{
  "username":"testename2",
  "password": "testepass2"

}
